dist: trusty
language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 5.4
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 5.5
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 5.5
    - php: hhvm
      env: DB=mariadb
      addons:
        mariadb: 5.5

    - php: 5.3
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 5.4
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 5.5
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: hhvm
      env: DB=mariadb
      addons:
        mariadb: 10.1

services:
  - mysql

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - mysql -e 'CREATE DATABASE mysql_test;'
  - mysql -e 'USE mysql_test; CREATE TABLE test_page ( page_id int(16) NOT NULL auto_increment, page_template varchar(255), page_type varchar(255), PRIMARY KEY (page_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:1.0.0
  - travis_retry composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --verbose --tap -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
